# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_BayesMultiLogit_dmvnrm_arma`, x, mean, sigma, logd)
}

#' Multinomial Logistic Regression using Data Augmentation
#' 
#' @description This function implements a data augmentation method for
#' multinomial logisitic regression using MCMC. The data augmentation method is
#' outlined in a paper by Jared D. Fisher and Kyle R. McEvoy titled
#' "Bayesian Multinomial Logistic Regression for Numerous Categories",
#' currently a work in progress. The sampler uses a Random-Walk Metropolis
#' algorithm for choosing proposals and acceptances.
#' 
#'
#' @param Y_ An N by C numeric matrix where the ith row is a set of
#' indicators for observation i of N total observations giving which
#' of the C categories the observation is classified into.
#' @param X_ An N by P numeric matrix where N is the total number of
#' observations and P is the total number of predictor variables the ith row
#' gives the values of the predictor variables for the ith outcome observation. 
#' @param n_sample positive integer giving the number of samples to draw as
#'  output after burn-in.
#' @param n_burn non-negative integer giving the number of samples of burn-in
#'  before the chain output is saved.
#' @param n_sigma_check non-negative integer gives the period for the number of
#' samples on which to automatically tune the step size of the random walk.
#' @param prior character with either values "flat" or "normal"
#' @param prior_mean a vector of length equal to P the number of predictors.
#' Giving the mean for the normal prior on the coefficient vector. Only use if
#' prior = "normal".
#' @param prior_var a P by P matrix giving the covariance matrix of the prior
#' coefficients. Note that covariance structure is assumed to be constant across
#' categories. Must be a positive semi-definite matrix. Only use with prior = 
#' "normal".
#' @param reference_cat Either NULL or an integer between 1 and C where C is
#' the total number of categories. If left NULL, coefficients for all
#' categories will be generated, leading to a loss of identifiability in the
#' coefficients. If an integer, all of the coefficents for that category will
#' be held constant at 0.
#' @return List object containing posterior_coef, the chain of coefficient
#' values as an P by C by n_sample array. And posterior_prob a N by C by
#' n_sample array containing the calculated probabilities of the observations
#' being classified into each of the C categories.
#' @examples 
#' Y <- matrix(0, nrow = 150, ncol = 3)
#' Y[1:50, 1] <- 1
#' Y[51:100, 2] <- 1
#' Y[101:150, 3] <- 1
#' X <- cbind(1, iris[ , 1:4])
#' X <- as.matrix(X)
#' out <- multilogit_C(Y, X, n_sample = 3000, n_burn = 1500, n_sigma_check = 20,
#'  step_size = 0.1, prior = "normal", reference_cat = 1)
#'  
#' out_2 <- multilogit_C(Y, X, n_sample = 2000, n_burn = 500, prior = "flat")
multilogit_C <- function(Y_, X_, n_sample = 1000L, n_burn = 200L, n_sigma_check = 20L, prior = "flat", step_size = 0.1, prior_mean = NULL, prior_var = NULL, reference_cat = NULL, probs = TRUE, progress = TRUE) {
    .Call(`_BayesMultiLogit_multilogit_C`, Y_, X_, n_sample, n_burn, n_sigma_check, prior, step_size, prior_mean, prior_var, reference_cat, probs, progress)
}

multilogit_C_ESS <- function(Y_, X_, n_sample = 1000L, n_burn = 200L, prior = "normal", prior_mean = NULL, prior_var = NULL, reference_cat = NULL, probs = TRUE, progress = TRUE) {
    .Call(`_BayesMultiLogit_multilogit_C_ESS`, Y_, X_, n_sample, n_burn, prior, prior_mean, prior_var, reference_cat, probs, progress)
}

#' Multinomial Logistic Regression using the Holmes-Held Method
#' 
#' This function implements the Holmes-Held method for
#' multinomial logistic regression described in their 2006 paper
#' 'Bayesian auxiliary variable models for binary and multinomial regression'
#' in Bayesian Analysis. The C++ code was written using the pseudo-code in
#' this paper as a template. Slower than \code{multilogit_hh_inv_C} but less error prone.
#' 
#'
#' @param Y An N by C numeric matrix where the ith row is a set of
#' indicators for observation i of N total observations giving which
#' of the C categories the observation is classified into.
#' @param X An N by P numeric matrix where the ith row gives
#' the values of the predictor variables for the ith outcome observation. 
#' @param v a P by P numeric matrix giving the covariance matrix of coefficients.
#' The function only accepts one matrix for all categories.
#' @param n_sample positive integer giving the number of samples to draw as
#'  output after burn-in.
#' @param n_burn non-negative integer giving the number of samples of burn-in
#'  before the chain output is saved.
#' @param probs If TRUE, categorical probabilities are calculated and returned.
#' @param progress If TRUE, the function will print its progress at every 1,000th
#' iteration.
#' @family Holmes-Held methods.
#' @seealso \code{mulitlogit_holmesheld} for a wrapper function with error
#' checking. \code{mulitlogit_hh_inv_C} for an alternative function which is faster,
#' but may have increased errors in matrix inversions.
#' @return List object containing posterior_coef, the chain of coefficient
#' values as a P by C by n_sample array. If probs are TRUE, the list will also include
#'  posterior_prob a N by C by n_sample array containing the calculated probabilities of
#'   the observation being classified into each of the C categories.
#' @examples 
#' Y <- matrix(0, nrow = 150, ncol = 3)
#' Y[1:50, 1] <- 1
#' Y[51:100, 2] <- 1
#' Y[101:150, 3] <- 1
#' X <- cbind(1, iris[ , 1:4])
#' X <- as.matrix(X)
#' v <- diag(10, ncol(X))
#' out <- multilogit_holmesheld_C(Y, X, v, n_sample = 4000, n_burn = 2000)
#' 
multilogit_holmesheld_C <- function(Y, X, v, n_sample = 1000L, n_burn = 200L, probs = TRUE, progress = TRUE) {
    .Call(`_BayesMultiLogit_multilogit_holmesheld_C`, Y, X, v, n_sample, n_burn, probs, progress)
}

#' Multinomial Logistic Regression using the Polya-Gamma Method
#' 
#' @description This function implements the Polya-Gamma method for
#' multinomial logistic regression. Rewritten for C++ by Jared Fisher
#' and Kyle McEvoy, but code originally written by Jesse Windle.
#' 
#' Copyright 2013 Nick Polson, James Scott, and Jesse Windle.
#' This file is part of BayesLogit, distributed under the GNU General Public
#' License version 3 or later and without ANY warranty, implied or otherwise.
#' 
#' @param Y_ NumericMatrix An N by C numeric matrix where the ith row is a set of
#' indicators for observation i of N giving which of the C categories the
#' observation is classified into.
#' @param X_ NumericMatrix An N by P numeric matrix where the ith row gives
#' the values of the predictor variables for the ith outcome observation. 
#' @param n_sample positive integer giving the number of samples to draw as
#'  output after burn-in.
#' @param n_burn non-negative integer giving the number of samples of burn-in
#'  before the chain output is saved.
#' @return list object containing posterior_coef, the chain of coefficient
#' values as an P by C by n_sample array. And posterior_prob a N by C by
#' n_sample array containing the calculated probabilities of the observations
#' being classified into each of the C categories.
#' 
#' @examples Y <- matrix(0, nrow = 150, ncol = 3)
#' Y[1:50, 1] <- 1
#' Y[51:100, 2] <- 1
#' Y[101:150, 3] <- 1
#' X <- cbind(1, iris[ , 1:4])
#' X <- as.matrix(X)
#' out2 <- multilogit_PG_C(Y, X, n_sample = 4000, n_burn = 2000)
multilogit_PG_C <- function(Y_, X_, n_sample = 1000L, n_burn = 200L) {
    .Call(`_BayesMultiLogit_multilogit_PG_C`, Y_, X_, n_sample, n_burn)
}

#' Multinomial Logistic Regression using the Holmes-Held Method
#' 
#' This function implements the Holmes-Held method for
#' multinomial logistic regression described in their 2006 paper
#' 'Bayesian auxiliary variable models for binary and multinomial regression'
#' in Bayesian Analysis. The C++ code was written using the pseudo-code in
#' this paper as a template. Faster than \code{multilogit_holmesheld_C} 
#' but more error prone.
#' 
#'
#' @param Y An N by C numeric matrix where the ith row is a set of
#' indicators for observation i of N total observations giving which
#' of the C categories the observation is classified into.
#' @param X An N by P numeric matrix where the ith row gives
#' the values of the predictor variables for the ith outcome observation. 
#' @param v a P by P numeric matrix giving the covariance matrix of coefficients.
#' The function only accepts one matrix for all categories.
#' @param n_sample positive integer giving the number of samples to draw as
#'  output after burn-in.
#' @param n_burn non-negative integer giving the number of samples of burn-in
#'  before the chain output is saved.
#' @param probs If set to TRUE, categorical probabilities are calculated and returned.
#' @param progress If TRUE, the function will print its progress at every 1,000th
#' iteration.
#' @family Holmes-Held methods.
#' @seealso \code{mulitlogit_holmesheld} for a wrapper function with error
#' checking. \code{mulitlogit_holmesheld_C} for an alternative function which is slower,
#' but should have fewer errors in matrix inversions.
#' @return List object containing posterior_coef, the chain of coefficient
#' values as a P by C by n_sample array. If probs are TRUE, the list will also include
#'  posterior_prob a N by C by n_sample array containing the calculated probabilities of
#'   the observation being classified into each of the C categories.
#' @examples 
#' Y <- matrix(0, nrow = 150, ncol = 3)
#' Y[1:50, 1] <- 1
#' Y[51:100, 2] <- 1
#' Y[101:150, 3] <- 1
#' X <- cbind(1, iris[ , 1:4])
#' X <- as.matrix(X)
#' v <- diag(10, ncol(X))
#' out <- multilogit_hh_inv_C(Y, X, v, n_sample = 4000, n_burn = 2000)
#' 
multilogit_hh_inv_C <- function(Y, X, v, n_sample = 1000L, n_burn = 200L, probs = TRUE, progress = TRUE) {
    .Call(`_BayesMultiLogit_multilogit_hh_inv_C`, Y, X, v, n_sample, n_burn, probs, progress)
}

